# Generated by rust2rpm 28
%bcond check 1
%global debug_package %{nil}

%global crate atom_syndication

Name:           rust-atom_syndication
Version:        0.12.7
Release:        %autorelease
Summary:        Library for serializing the Atom web content syndication format

# Upstream license specification: MIT/Apache-2.0
License:        MIT OR Apache-2.0
URL:            https://crates.io/crates/atom_syndication
Source:         %{crates_source}

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
Library for serializing the Atom web content syndication format.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE-APACHE
%license %{crate_instdir}/LICENSE-MIT
%doc %{crate_instdir}/CHANGELOG.md
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+builders-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+builders-devel %{_description}

This package contains library source intended for building other packages which
use the "builders" feature of the "%{crate}" crate.

%files       -n %{name}+builders-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+derive_builder-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+derive_builder-devel %{_description}

This package contains library source intended for building other packages which
use the "derive_builder" feature of the "%{crate}" crate.

%files       -n %{name}+derive_builder-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+never-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+never-devel %{_description}

This package contains library source intended for building other packages which
use the "never" feature of the "%{crate}" crate.

%files       -n %{name}+never-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+serde-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+serde-devel %{_description}

This package contains library source intended for building other packages which
use the "serde" feature of the "%{crate}" crate.

%files       -n %{name}+serde-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+with-serde-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+with-serde-devel %{_description}

This package contains library source intended for building other packages which
use the "with-serde" feature of the "%{crate}" crate.

%files       -n %{name}+with-serde-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
